---
- name: Ensure IIS is uninstalled
  hosts: windows
  become: yes
  become_user: Administrator
  tasks:
    - name: Ensure IIS Server is uninstalled
      win_feature:
        name:  Web-Server
        state: absent
      tags:
        - remove-iis
